### ISSUE TITLE
Logic flaw in restLikes event listener

### ISSUE THREAD

**Issue by swissspidy** [wearerequired/rest-likes#86]
Custom JS events were added in #59.

Since then, we check all like buttons again by listening to this event:

https://github.com/wearerequired/rest-likes/blob/35efb39d587e4e485b4d83a06023b88b89f9ab84/js/src/rest-likes.js#L276-L279

Before that, like buttons were checked again for the `post-load` event. See https://github.com/wearerequired/rest-likes/commit/a4127ce66ace5e3133da291f71ff38748df67998

The ideas page on magazin.swisscom.ch leveraged this to update like buttons accordingly.

Listening to the `restLikes` event and checking _all_ buttons is very expensive though. Especially since the plugin fires that event itself...

We should either remove that event listener if it's not needed, or at least only process the specific like button the event is for.

**Comment by ocean90** [comment]
Maybe we can replace it with a `MutationObserver` which checks for elements with the `[data-rest-like-button]` attribute.
